//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFinderTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Business_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business_Owner()
        {
            this.Business_detail = new HashSet<Business_detail>();
            this.Contact_Us = new HashSet<Contact_Us>();
        }
    
        [Key]
        public int busi_id { get; set; }
        [Required(ErrorMessage = "Please Enter Your Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string email { get; set; }

        [Required(ErrorMessage = "Enter Your Valid Mobile Number")]
        [MaxLength(10)]
        public string phno { get; set; }

        [Required(ErrorMessage = "Please Enter Business Address")]
        public string address { get; set; }

        public string img { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImgFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Business_detail> Business_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_Us> Contact_Us { get; set; }
    }
}
