//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFinderTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Business_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business_detail()
        {
            this.Reviews = new HashSet<Review>();
        }

        [Key]
        public int bid { get; set; }

        [Required(ErrorMessage = "Enter BusinessDetail Name")]
        public string bname { get; set; }


        public Nullable<int> busi_id { get; set; }


        public Nullable<int> subcat_id { get; set; }


        public Nullable<int> area_id { get; set; }

        [Required(ErrorMessage = "Please Enter Business Address")]
        public string address { get; set; }

        [Required]
        public string pincode { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string busi_email { get; set; }

        [Required(ErrorMessage = "Enter Your Valid Mobile Number")]
        [MaxLength(10)]
        public string phno { get; set; }

        public string img { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImgFile { get; set; }

        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        public string time { get; set; }

        [MaxLength(1000)]
        public string description { get; set; }

        public virtual Area Area { get; set; }
        public virtual Business_Owner Business_Owner { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
