//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFinderTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Faq
    {
        [Key]
        public int faq_id { get; set; }

        [Required(ErrorMessage = "Enter Your  Name")]
        public string name { get; set; }

        [Required(ErrorMessage = "Please Enter Question")]
        public string question { get; set; }

        [Required(ErrorMessage = "Please Enter Answer")]
        public string answer { get; set; }
    }
}
