//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFinderTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        [Key]
        public int rid { get; set; }

        [Required]
        public string rate { get; set; }

        [MaxLength(1000)]
        public string description { get; set; }

        [Required]
        public Nullable<int> bid { get; set; }
        public Nullable<System.DateTime> date { get; set; }

        public virtual Business_detail Business_detail { get; set; }
    }
}
