//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFinderTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Subcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subcategory()
        {
            this.Business_detail = new HashSet<Business_detail>();
        }

        [Key]
        public int subcat_id { get; set; }


        public Nullable<int> category_id { get; set; }

        [Required(ErrorMessage = "Enter SubCategory name")]
        public string subcat_name { get; set; }


        public string subcat_img { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImgFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Business_detail> Business_detail { get; set; }
        public virtual Category Category { get; set; }
    }
}
